/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package razorvine.ksim68k

import java.nio.ByteBuffer
import kotlin.test.Test


class LibraryTest {
    @Test fun testSomeLibraryMethod() {
        val memory = Memory(ShortArray(20000))
        Ksim68k.use_memory(memory)
        Ksim68k.init()
        println("VALID? ${Ksim68k.is_valid_instruction(0x0001, Cpu.M68030)}")
        Ksim68k.set_cpu_type(Cpu.M68030)
        val buffer = ByteBuffer.allocateDirect(900);
        println(Ksim68k.get_context(buffer))
        println(Ksim68k.context_size())
        println(Ksim68k.get_reg(null, Register.A0))
        val disassem = ByteArray(200)
        println(Ksim68k.disassemble(disassem, 0, Cpu.M68030))
        println(disassem)
    }
}
