/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package razorvine.ksim68k

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun testSomeLibraryMethod() {
        val musashi = Musashi.INSTANCE
        assertTrue(musashi.testmethod())
    }
}
